// ShapeScript document

/// Catamaran Propulsion System â€” Holder Bracket

//////////////////////////////////////////////////////////////////////////////

detail 90
rotate 0  0  -0.5  /// CAD mode

//////////////////////////////////////////////////////////////////////////////

define INCH_IN_MM                             25.399999619  /// mm
define GAP                                    0.2  /// mm
/// Holders
define HOLDER_THICKNESS                       (0.25 * INCH_IN_MM)  /// (1/4")
define HOLDER_LENGTH                          32       /// mm
define HOLDER_WIDTH                           32       /// mm
define HOLDER_HEIGHT                          40       /// mm
define HOLDER_SCREW_HOLE_DIAMETER             (5/16 * INCH_IN_MM)  /// mm (5/16")

//////////////////////////////////////////////////////////////////////////////

define HOLDER {
    color 0.75  0.75  0.5

    difference {
        difference {
            cube {
                size HOLDER_WIDTH  HOLDER_LENGTH  HOLDER_HEIGHT
            }

            cube {
                size HOLDER_WIDTH - HOLDER_THICKNESS  HOLDER_LENGTH - HOLDER_THICKNESS  HOLDER_HEIGHT
                position HOLDER_THICKNESS / 2  HOLDER_THICKNESS / 2
            }
        }

        /// Hole for securing to the support
        cylinder {
            size (HOLDER_SCREW_HOLE_DIAMETER + GAP * 2)  HOLDER_THICKNESS
            position (HOLDER_THICKNESS / 2)  -(HOLDER_LENGTH / 2 - HOLDER_THICKNESS / 2)
        }

        /// Hole for securing to the rail
        cylinder {
            size (HOLDER_SCREW_HOLE_DIAMETER + GAP * 2)  HOLDER_THICKNESS
            orientation 0.5
            position -(HOLDER_WIDTH / 2 - HOLDER_THICKNESS / 2)  (HOLDER_THICKNESS / 2)
        }
    }
}

//////////////////////////////////////////////////////////////////////////////

HOLDER {
}

//////////////////////////////////////////////////////////////////////////////

print "[HOLDER] thickness: " HOLDER_THICKNESS "mm"
print "[HOLDER] hole diameter: " (HOLDER_SCREW_HOLE_DIAMETER + GAP * 2) "mm"
print "[HOLDER] distance from corner to screw hole's center: " (HOLDER_WIDTH / 2 + HOLDER_THICKNESS / 2) "mm"
