// ShapeScript document

/// Ahydrodynamic Paddle Blade

detail 128
rotate 0 0 -0.5  /// CAD mode

define SHAFTDIAMETER                      35.5  /// mm
define BLADESHAFTBUTTONDIAMETER            8
define BLADESHAFTSLOTDEPTH                54
define BLADESHAFTSLOTBUTTONHOLEPOSITION   22
define BLADEWALLTHICKNESS                  3    /// mm
define BLADELENGTH                       540
define BLADEWIDTH                        270

define PADDLEBLADE {
    /// Shaft connection slot
    union {
        difference {
            difference {
                cylinder {
                    size (SHAFTDIAMETER + BLADEWALLTHICKNESS * 2)  BLADESHAFTSLOTDEPTH
                }

                difference {
                    cylinder {
                        position 0  BLADESHAFTSLOTDEPTH / 2 - BLADEWALLTHICKNESS / 4  0
                        size SHAFTDIAMETER + BLADEWALLTHICKNESS * 2   BLADEWALLTHICKNESS / 2
                    }

                    extrude {
                        circle {
                            size BLADEWALLTHICKNESS
                        }
                        along circle {
                            orientation 0 0 0.5
                            position 0  BLADESHAFTSLOTDEPTH / 2 - BLADEWALLTHICKNESS / 2  0
                            size SHAFTDIAMETER + BLADEWALLTHICKNESS
                        }
                    }
                }
            }

            cylinder {
                size SHAFTDIAMETER  BLADESHAFTSLOTDEPTH
            }

            cylinder {
                size        BLADESHAFTBUTTONDIAMETER  BLADEWALLTHICKNESS * 2
                orientation 0  0  0.5
                position    0 (BLADESHAFTSLOTDEPTH / 2 - BLADESHAFTSLOTBUTTONHOLEPOSITION - BLADESHAFTBUTTONDIAMETER / 2)  (SHAFTDIAMETER / 2)
            }
        }

        difference {
            sphere {
                size (SHAFTDIAMETER + BLADEWALLTHICKNESS * 2)  (BLADESHAFTSLOTDEPTH * 4)
                position 0  -(BLADESHAFTSLOTDEPTH/2)
            }

            cylinder {
                size (SHAFTDIAMETER + BLADEWALLTHICKNESS * 2)  BLADESHAFTSLOTDEPTH * 4 / 2
                position 0  BLADESHAFTSLOTDEPTH/2
            }
        }
        
    }

    /// Blade
    difference {

        sphere {
            size      BLADELENGTH   SHAFTDIAMETER * 2   BLADEWIDTH
            orientation 0.5 0 0.5
            position  0  -(BLADELENGTH / 2 + BLADESHAFTSLOTDEPTH/2)
        }

        union {
            sphere {
                size      BLADELENGTH * 3   SHAFTDIAMETER * 2   BLADEWIDTH
                orientation 0.5 0 0.5
                position  0  -(BLADELENGTH / 2 + BLADESHAFTSLOTDEPTH/2 + BLADELENGTH / (3 / 2))  SHAFTDIAMETER
            }

            sphere {
                size      BLADELENGTH * 3   SHAFTDIAMETER * 2   BLADEWIDTH
                orientation 0.5 0 0.5
                position  0  -(BLADELENGTH / 2 + BLADESHAFTSLOTDEPTH/2 + BLADELENGTH / (3 / 2))  -SHAFTDIAMETER
            }
        }
        
    }
}

difference {
    PADDLEBLADE

    cube {
        size 0 // (BLADEWIDTH)  ((BLADELENGTH + BLADESHAFTSLOTDEPTH) / 3)  (BLADEWIDTH)
        position 0 -((BLADELENGTH+BLADESHAFTSLOTDEPTH)/2 - BLADESHAFTSLOTDEPTH/2)-((BLADELENGTH + BLADESHAFTSLOTDEPTH) / 3)
    }
    cube {
        size 0 // (BLADEWIDTH)  ((BLADELENGTH + BLADESHAFTSLOTDEPTH) / 3)  (BLADEWIDTH)
        position 0 -((BLADELENGTH+BLADESHAFTSLOTDEPTH)/2 - BLADESHAFTSLOTDEPTH/2)
    }
    cube {
        size 0 // (BLADEWIDTH)  ((BLADELENGTH + BLADESHAFTSLOTDEPTH) / 3)  (BLADEWIDTH)
        position 0 -((BLADELENGTH+BLADESHAFTSLOTDEPTH)/2 - BLADESHAFTSLOTDEPTH/2)+((BLADELENGTH + BLADESHAFTSLOTDEPTH) / 3)
    }
}
